language: objective-c
osx_image: xcode8.3
before_install:
- pod update
- brew outdated xctool || brew upgrade xctool
script:
- xcodebuild -workspace Project.xcworkspace -scheme iOS -sdk iphonesimulator build test -destination 'platform:iOS Simulator, id:0EB7E0E4-915F-497E-9D1C-934A10FA82E3, OS:10.3.1, name:iPhone 6'
