let startTestNotificationKey = "com.IeuanTudurPeace.startBleepTestNotificationKey"
let stopTestNotificationKey = "com.IeuanTudurPeace.stopBleepTestNotificationKey"
let startedNewLapNotificationKey = "com.IeuanTudurPeace.startedNewLapNotificationKey"
let leveledUpNotificationKey = "com.IeuanTudurPeace.leveledUpNotificationKey"
let lapedUpNotificationKey = "com.IeuanTudurPeace.lapedUpNotificationKey"
